#PROGRAM TO FIND THE AREA OF THE RECTANGLE
l=int(input("ENTER THE LENGTH OF THE RECTANGLE\n"))
b=int(input("ENTER THE BREADTH OF THE RECTANGLE\n"))    
print("AREA OF THE RECTANGLE is",l*b,"square units")
